# Generated by Django 5.1 on 2024-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MobileViewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('primary_image', models.ImageField(upload_to='uploads')),
                ('img2', models.ImageField(upload_to='uploads')),
                ('img3', models.ImageField(upload_to='uploads')),
                ('img4', models.ImageField(upload_to='uploads')),
                ('img5', models.ImageField(upload_to='uploads')),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.CharField(max_length=10000)),
                ('location', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=8)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
            ],
        ),
    ]
