# Generated by Django 5.1 on 2024-08-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
