# Generated by Django 5.1 on 2024-08-24 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_packagemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='id',
            field=models.CharField(default=uuid.UUID('2270b323-2588-48c7-a126-54e6a5d3932e'), max_length=1000, primary_key=True, serialize=False),
        ),
    ]
