# Generated by Django 5.1 on 2024-08-24 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_packagemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='id',
            field=models.CharField(default=uuid.UUID('1c9f3ac8-6cc1-401f-95d9-60989c28bdcf'), max_length=1000, primary_key=True, serialize=False),
        ),
    ]
