# Generated by Django 5.1 on 2024-08-25 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_packagemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='id',
            field=models.CharField(default=uuid.UUID('bd503ef2-f0ec-4847-af8f-5a1274b67fe3'), max_length=1000, primary_key=True, serialize=False),
        ),
    ]
