# Generated by Django 5.1 on 2024-08-25 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_packagemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='id',
            field=models.CharField(default=uuid.UUID('61c9922c-8023-4c93-9dc2-ce6133ac733d'), max_length=1000, primary_key=True, serialize=False),
        ),
    ]
